### ISSUE TITLE
Handle non-square images

### ISSUE THREAD

**Issue by nikolajovickg** [csia-pme/djl-image-sam#1]
Hello, SAM can handle non square images, whereas it seems that I can't do it with this djl model. If the non square image is presented to the model, embeddings are skewed

**Comment by leonardcser** [comment]
This is expected as I've hardcoded the image to be 1024x1024 (https://github.com/csia-pme/djl-image-sam/blob/main/pytorch_convert/sam_predictor_base_model.py).

If you would like to make it work for any image size, have a look at the original implementation. Instead of predicting with the model, there is a wrapper class SamPredictor (https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/predictor.py) that handles this logic.

When setting the image (`set_image`), it resizes the image with the ResizeLongestSide class (https://github.com/facebookresearch/segment-anything/blob/main/segment_anything/utils/transforms.py) and then transforms the prediction to the original image size.

Most of this code would need to be reimplemented in the target language (Java in this case) as it is difficult convert the SamPredictor class to TorchScript.

Hope this helps!

**Comment by nikolajovickg** [comment]
Sure, thanks for the pointers!
